version: "3.9"

services:
  lmps-service:
    image: "172.16.4.62:5000/noh/lmps-payment:v1.0.0"
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      TZ: "Asia/Bangkok"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - lmps_payment_logs:/usr/app/logs
    networks:
      - lbb_network

networks:
  lbb_network:
    external: true

volumes:
  lmps_payment_logs: