
server:
  port: 8084
#spring:
#  datasource:
#    continue-on-error: true # ໃຫ້ເຮັດວຽກຕໍ່ເຖິງຈະມີ Error ຕອນ Init DB
#    url: jdbc:oracle:thin:@//localhost:1521/xe
#    username: myuser
#    password: mypassword
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    database-platform: org.hibernate.dialect.Oracle12cDialect
#    show-sql: true
external:
  api:
    client:
      connect-timeout: 5000
      read-timeout: 10000

management:
  tracing:
    sampling:
      probability: 1.0  # ເກັບ Trace ທຸກ Request (ຖ້າໃຊ້ໃນ Production ຕົວຈິງອາດຈະປັບເປັນ 0.1)