
server:
  port: 8084
spring:
  datasource:
#    url: jdbc:oracle:thin:@//172.16.4.79:1521/LBBMBUAT02.lbb.local
#    username: admin_mbuat
#    password: Admin123##
    url: jdbc:oracle:thin:@//172.16.4.79:1521/cdbmbuat.lbb.local
    username: mb_uat
    password: qwertyui
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: false
external:
  api:
    client:
      connect-timeout: 5000
      read-timeout: 10000
    core-banking:
      url: http://172.16.4.113:8082
    m-smart:
      url: http://172.16.4.18:7001

minio:
  endpoint: https://s3-uat.laobullionbank.com
  access-key: admin_iquri
  secret-key: admin@iquri@2025
  bucket: lbb-mb-uat

management:
  tracing:
    sampling:
      probability: 1.0  # ເກັບ Trace ທຸກ Request (ຖ້າໃຊ້ໃນ Production ຕົວຈິງອາດຈະປັບເປັນ 0.1)