
server:
  port: 8084
spring:
  datasource:
    url: jdbc:oracle:thin:@//172.16.4.79:1521/cdbmbuat.lbb.local
    username: mb_uat
    password: qwertyui
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: false
external:
  api:
    client:
      connect-timeout: 5000
      read-timeout: 10000
    core-banking:
      url: http://localhost:8082/api/corebanking
    m-smart:
      url: http://172.16.4.18:7001

management:
  tracing:
    sampling:
      probability: 1.0  # ເກັບ Trace ທຸກ Request (ຖ້າໃຊ້ໃນ Production ຕົວຈິງອາດຈະປັບເປັນ 0.1)