spring:
  application:
    name: lbb-lmps
  profiles:
    active: local

server:
  servlet:
    context-path: /
management:
  tracing:
    sampling:
      probability: 1.0  # ເກັບ Trace ທຸກ Request (ຖ້າໃຊ້ໃນ Production ຕົວຈິງອາດຈະປັບເປັນ 0.1)

external:
  api:
    m-smart:
      path-root: /m-smart
      path-member-list: /lmps/member/list
      path-inq-out: /lmps/out/inquiry/register
      path-trf-out: /lmps/out/transfer
      path-build-qr: /qr/generate
      path-qr-info: /qr/info
    cbs:
      path-root: /api/corebanking
      path-getrate: /getRate
      path-p2p-transfer: /p2p/transfer